language: julia
julia:
- 1.1
script:
- ./generate_notebooks.sh
after_success:
- ./push.sh
env:
  matrix:
    secure: Op1xkbui4pE+3YwpLzEIIvwIP8PDFUPGXpmP1ZsjHT3lyvLybNZeFbWMKT3gml0q3VZ0uXELQ2/uy1/HNa9ZEKkIlhJnxrI4OHANeES14ZfvYAPUMn0SdDr2UUpbaxPOMdt2IPUcqMt5IPJmzm+Oc2W+3ycyWB1N9V98+EZ9DAwRk8sGMEnH9GBA4NaBzZhwK142il5UTfLiIUZ1C0o0sWd8J3iowGDnvCYJWPCdcWy9DMFaBk6uCdUn+9Z4QAq967iZbCYOmf3L3fDMwqfEYb9XnB7xIajDYJ0fVREYb8Lp1mufXvU6ZhAo0kkMaNvkTsKUJSgxLDQqgFKpk6YtBVRj0jZ0BJXk17KqibID2nCQUs1H2bqNJx8glYeUOIcJ12VeyAABJjuuyk1XqLMP+3R0sU7hCfwNS35x5lyB8MV12ldZjJ+L2dRYFXtfP9xjb9jgXytuB1ecG/uV/YD3MGYoA02zcrtbku1bSWxV1rsjVSom9L3ZxaaQkwmXaMxZywtNGuq2Rhdep3ehVb/srkIwYVruYTurhWR041d3kxSQrbInoec0W92eBcwZHVRgzZQ78Xg1L5j4xziB59xq0l9fMZ9OtG+UDk/vTxSxk3peNYUXq7NIA4ct6KfbX0Po1luVTl4Q+7RJcybmkkN5hCkgb+U8sQwJGrm0fTl2wzE=
