[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PowerDynBase = "7ffb48b1-f436-5a59-a310-b4407da33972"
PowerDynOperationPoint = "95be4243-a2fd-5eef-a7d1-2e97978993e7"
PowerDynSolve = "b2d36aa5-a2b1-5d23-8bd9-f353e61de00d"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
Julia = "^1.0"
PowerDynamics = "^0.4.1"
