[deps]
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PowerDynamics = "cc46b21f-1b17-51c2-b642-af74c3d3a8be"

[compat]
Julia = "^1.0"
PowerDynamics = "^2.1.0"
